on:
  push:
    branches:
      - master
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v2
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: npx semantic-release
      - name: VSCode release extension
        uses: lannonbr/vsce-action@master
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: 'publish -p $VSCE_TOKEN'
